name: Convert Word to PPT using manual textboxes and auto-fit

on:
  push:
    paths:
      - 'input.docx'
  workflow_dispatch:

jobs:
  convert_ppt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python libraries
        run: |
          pip install --upgrade pip
          pip install python-docx python-pptx==0.6.21

      - name: Run conversion script
        run: |
          python convert.py input.docx output.pptx

      - name: Upload PPT as artifact
        uses: actions/upload-artifact@v4
        with:
          name: presentation
          path: output.pptx 