name: Convert Word to PPT

on:
  push:
    paths:
      - input.docx
  workflow_dispatch:

jobs:
  convert_ppt:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          pip install --upgrade pip
          pip install python-docx python-pptx==0.6.21

      - name: Lancer le script de conversion
        run: |
          python convert.py input.docx output.pptx

      - name: Publier le PPT en artifact
        uses: actions/upload-artifact@v3
        with:
          name: PresentationResult
          path: output.pptx
